sudo: required
services:
- docker
env:
  global:
  - VERSIONS="5.5,5.6,7.0"
  - secure: iH45X+LFovpHQxkyZLIcs5/fr1x9i6WKk7hFmlePMkBh7jl3MLzdnKx+1nng9oQSEmb//H+uPpyaBZECiRX0MMWDKZN11mSjBmJ/sUgDUP1znyz6e0NWGk5zKsMdOkTHhLcA3516ar5Nw8vmoUhm2IUFa5ivOpIpWhGbesDNrf6eOd9tQPfH/Eo7Qb2zd/6nK3PohQ20DBkS6I8YuAsbswOwRAhnw70rPrCzhCLQsYRdo/gEpzb8f8Ovd1yx8bawZtWqR41tH8P/yhQc1zFnDwfuoXcqsMrOKU8f0eS8o3D8OSIFiKyhZSNaUX3uypiW7CbGSf41xxI65YI6NiTGpnM+jDVfysEVNm4L1ZOQK+eDQMsBgVwjr+YFwjx3P6E6rfH1WIgAI5UFcG91V/Aagd/X9UhNWT8UCowhNziNBLYSTTXlx2NFKDMoDXblGtTKLiAD/7a/LsLM9yPfiRzfvDBgelymItQK6sbfSVmV65GdsFi8ybE0R2DsDzpxKhwDhuOG6UFSwGAdi1zdYmnQF0cDhhPETRFMCRhAhQfu5nRFHR2+ox/kmTlI9++gHhrVJ/U8RiMJ/WfKrQKwbJZx5wZqZuGTZ+5JslzvH0HSIhj2yxMVvILiPyU15uHoT5sA15fOjDvoa6C6mafO9nFaIleIut4nWSYsCryS5AFmbg0=
script:
- ". test/run"
notifications:
  slack:
    secure: UAJyvA+mafjFJNAyjxz+0B/dmlz9yRRXjqG9D3K276q23mgM5y2fbvr+kLW3A7DNj7MYnzdGvk9FXlvfTFNDNCSYFR2rmh4cUZ9qbnd/U1dI/vdiZk2JdbXaY0J4yTIp2Xtwx7cigSlK9e7v0gOCALq99Mv6hNjJAwljnYBtkuGquBcEBW8jO1x9616ykW6ocWFWIQeyBFijIlY0UiGa/m97lJzpTUQcrFc5DriDR+o26O3c4voOunef40PUfdeYcgx8KwRpMbi2M48/kGBP3OCfwlevwtf4LYXrSZg6U01NNgTX2hXsszTKWBi2WLfct76JcGj4TlsdXEIC9WY6DB4ZlimcuT8B9N7pOS1pF5XLzMT6yZBqYm40fg5K9f151OqvnN/59mkBpeZUvL4+5sUd50dnyfxApo7ZjYz6b/GxwOYxJPHZWatkMGRdzNSEGz473pRZVV7D41H0SlzDfSewtRLf4wBYaLJBA3VUoPptdH5G5namIZWcuH3XACQAnGQ5iJ5boJlWJh0Im/vhp+zwKolUlVon6OAtNFua7DYey/jD+AXPOIIj/NDxrtCa09/IF+UVNSx9BLgYOKtpy3lH/ZBcAzmyRW4hW5uFu1gGK0/YjySYYt7Qr/cZEKghyjgS5v3FJ/7Truz/nF1FhA+TIm29fJ0S+sVsYjuLol0=
